{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- if or (.Values.fabric_actions.cryptogen) (.Values.fabric_actions.create_channel) }}

{{- $HlfDomain      := .Values.hlf_domain }}
{{- $BaseDir        := .Values.workdir }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fabric-ops.fullname" $ }}-configtx
  labels:
    {{- include "fabric-ops.labels" $ | nindent 4 }}
  annotations:
data:
 configtx.yaml: |
  Organizations:
  {{- range .Values.admin_organizations }}
    - &{{ .org_name }}
        Name: {{ .org_name }} 
        ID: {{ .org_name }}
        {{- $Msp_dir := printf "%s/%s/%s/%s" $BaseDir .org_name .admin_identity "msp" }}
        MSPDir: {{ .msp_dir | default $Msp_dir }}
      {{- if eq "orderer" .org_type }}
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('{{ .org_name }}.member')"
            Writers:
                Type: Signature
                Rule: "OR('{{ .org_name }}.member')"
            Admins:
                Type: Signature
                Rule: "OR('{{ .org_name }}.admin')"
        OrdererEndpoints:
        {{- range .orderer_identities }}
            - {{ printf "%s.%s:%s" .identity_name $HlfDomain .port }}
        {{- end }}        
      {{- end }}
      {{- if eq "consortium" .org_type }}
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('{{ .org_name }}.admin', '{{ .org_name }}.peer', '{{ .org_name }}.client')"
            Writers:
                Type: Signature
                Rule: "OR('{{ .org_name }}.admin', '{{ .org_name }}.client')"
            Admins:
                Type: Signature
                Rule: "OR('{{ .org_name }}.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('{{ .org_name }}.peer')"
        AnchorPeers:
            {{- range .anchor_peers }}
            - Host: {{ .host }}
              Port: {{ .port }}
            {{- end }}       
      {{- end }}
  {{- end }}
  Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true
  Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities
  Orderer: &OrdererDefaults
    OrdererType: etcdraft
    BatchTimeout: 1s
    BatchSize:
        MaxMessageCount: 150
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 99 MB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
  Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "ANY Admins"
    Capabilities:
        <<: *ChannelCapabilities
  Profiles:
  {{- if eq "ConsortiumProfile" .Values.configTxProfileType }}
    ConsortiumProfile:
        Consortium: {{ $.Values.consortiumName }}
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
              {{- range .Values.admin_organizations }}
              {{- if eq "consortium" .org_type }}
                - *{{ .org_name }}
              {{- end }}
              {{- end }}
            Capabilities:
                <<: *ApplicationCapabilities
  {{- end }}
  {{- if eq "OrdererEtcdRaftProfile" .Values.configTxProfileType }}
    OrdererEtcdRaftProfile:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
    {{- range .Values.admin_organizations }}
    {{ $Org_name := .org_name }}
      {{- if eq "orderer" .org_type }}
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                {{- range .orderer_identities }}
                {{- $msp_dir  := printf "%s/%s/%s/%s" $BaseDir $Org_name .identity_name "tls" }}
                - Host: {{ printf "%s.%s" .identity_name $HlfDomain }}
                  Port: {{ .port }}
                  ClientTLSCert: {{ $msp_dir }}/server.crt
                  ServerTLSCert: {{ $msp_dir }}/server.crt
                {{- end }}
            Addresses:
            {{- range .orderer_identities }}
               - {{ printf "%s.%s:%s" .identity_name $HlfDomain .port }}
            {{- end }}
            Organizations:
            - *{{ $Org_name }}
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *{{ $Org_name }}
      {{- end }}
    {{- end }}
        Consortiums:
          {{ $.Values.consortiumName }}:
            Organizations:
            {{- range .Values.admin_organizations }}
            {{- if eq "consortium" .org_type }} 
             - *{{ .org_name }}
            {{- end }}
            {{- end }}
  {{- end }}
{{- end }}