{{/*
Copyright National Payments Corporation of India. All Rights Reserved.
SPDX-License-Identifier:  GPL-3.0
*/}}

{{- if .Values.fabric_actions.create_channel | default false }}

{{ $BankName               := .Values.nameOverride }}
{{ $CorePeerMspConfigPath  := printf "%s%s%s%s%s" .Values.workdir "/" $BankName "/admin" "/msp" }}

{{- range .Values.app_channels }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-{{ . }}
  labels:
    {{- include "fabric-ops.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fabric-ops.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fabric-ops.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      initContainers:
      containers:
        - name: cli
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          workingDir: {{ $.Values.workdir }}/peer
          command: ["/bin/sh","-c"]
          args:
           - /scripts/fabric_create_channel.sh {{ . }};
          tty: true
          env: 
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_LOCALMSPID
              value: {{ $BankName }}
            - name: CORE_PEER_MSPCONFIGPATH
              value: {{ $.Values.core_peer_mspconfigpath_override | default $CorePeerMspConfigPath }}
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: GOPATH
              value: /opt/gopath
            - name: ORDERER_CA
              value: {{ $.Values.tlsca_tls_certfile | default "/tmp/tlsca-cert.pem" }}
          volumeMounts:
            - name: fabric-ops
              subPath: config.yaml
              mountPath: /tmp/config.yaml
            - name: fabric-ops
              subPath: fabric_enroll.sh
              mountPath: /scripts/fabric_enroll.sh
            - name: scripts
              subPath: fabric_create_channel.sh
              mountPath: /scripts/fabric_create_channel.sh
            - name: configtx
              subPath: configtx.yaml
              mountPath: {{ $.Values.workdir }}/peer/configtx.yaml
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}
            defaultMode: 0777
        - name: configtx
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}-configtx
            defaultMode: 0777
        - name: fabric-ops
          configMap:
            name: {{ include "fabric-ops.fullname" $ }}-functions
            defaultMode: 0777
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
{{- end }}